DROP TABLE ORCHESTRATION_PROCESS_EXECUTION IF EXISTS;
CREATE TABLE ORCHESTRATION_PROCESS_EXECUTION
(
	ORCHESTRATION_PROCESS_EXECUTION_ID	                    INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	ORCHESTRATION_PROCESS_ID	                            INT NOT NULL,
	EVENT_INSTANCE_ID                                       INT,
	CLIENT_RUN_ID                                           VARCHAR(128),
	SCENARIO_TYPE			 	    						VARCHAR(32),
	RUN_TYPE												VARCHAR(32),
	CREATE_TIME	                                            TIMESTAMP NOT NULL,
	START_TIME	                                            TIMESTAMP,
	END_TIME	                                            TIMESTAMP,
	STATUS	                                                VARCHAR(16),
	EXIT_CODE	                                            VARCHAR(16),
	EXIT_MESSAGE	                                        VARCHAR(10000)
) ORGANIZE BY ROW DISTRIBUTE ON RANDOM IN TBS_<env>;
ALTER TABLE ORCHESTRATION_PROCESS_EXECUTION ADD CONSTRAINT ORCHESTRATION_PROCESS_EXECUTION_PK PRIMARY KEY (ORCHESTRATION_PROCESS_EXECUTION_ID);
